# Generated by Django 2.1.5 on 2019-07-14 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Default', max_length=250)),
                ('images', models.FileField(default='/photo.png', upload_to='posts/%Y/%m/%d')),
                ('author', models.CharField(default='author', max_length=250)),
                ('categories', models.CharField(default='categories', max_length=250)),
                ('tags', models.CharField(default='tags', max_length=250)),
                ('visibility', models.CharField(default='public', max_length=250)),
                ('commnets', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('date_create', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
