# Generated by Django 2.1.5 on 2019-04-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(default='/default/default.png', upload_to='images/'),
        ),
    ]
