# Generated by Django 2.1.5 on 2019-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190419_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(default='/photo.png', upload_to='images'),
        ),
    ]
